### ISSUE TITLE
Download failed on Linux and windows

### ISSUE THREAD

**Issue by Fak3** [AnimMouse/setup-ffmpeg#2]
Download failed on Linux and windows, details can be seen at
https://github.com/Fak3/enjam/actions/runs/11326826202/job/31496566748#step:3:1

**Comment by AnimMouse** [comment]
FFmpeg 7.0 has been removed on [BtbN/FFmpeg-Builds](https://github.com/BtbN/FFmpeg-Builds/releases/tag/latest). Please use `7.1`.

**Comment by Fak3** [comment]
Thanks!
